name: 'Markdown Grammar Checker'
description: 'Checks markdown files for grammar, style, and formatting issues using AI'
author: 'Haimantika Mitra'

inputs:
  github-token:
    description: 'GitHub token for accessing PR files'
    required: true
    default: ${{ github.token }}
  do-api-token:
    description: 'DigitalOcean API token'
    required: true
  do-agent-base-url:
    description: 'DigitalOcean AI agent base URL'
    required: true
  file-pattern:
    description: 'Glob pattern for files to check'
    required: false
    default: '**/*.md'
  exclude-pattern:
    description: 'Glob pattern for files to exclude'
    required: false
    default: '**/node_modules/**'

runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: node ${{ github.action_path }}/index.js
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_DO_API_TOKEN: ${{ inputs.do-api-token }}
        INPUT_DO_AGENT_BASE_URL: ${{ inputs.do-agent-base-url }}
        INPUT_FILE_PATTERN: ${{ inputs.file-pattern }}
        INPUT_EXCLUDE_PATTERN: ${{ inputs.exclude-pattern }}

branding:
  icon: 'edit-3'
  color: 'blue'