name: 'Markdown Grammar Checker'
description: 'Checks markdown files for grammar, style, and formatting issues using AI'
author: 'Haimantika Mitra'

inputs:
  github-token:
    description: 'GitHub token for accessing PR files'
    required: true
    default: ${{ github.token }}
  do-api-token:
    description: 'DigitalOcean API token'
    required: true
  do-agent-base-url:
    description: 'DigitalOcean AI agent base URL'
    required: true
  file-pattern:
    description: 'Glob pattern for files to check'
    required: false
    default: '**/*.md'
  exclude-pattern:
    description: 'Glob pattern for files to exclude'
    required: false
    default: '**/node_modules/**'

runs:
  using: "composite"
  steps:
    - run: npm install --no-package-lock
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: |
        echo "Debugging environment variables:"
        echo "DO_API_TOKEN set: ${{ inputs.do-api-token != '' }}"
        echo "DO_AGENT_BASE_URL set: ${{ inputs.do-agent-base-url != '' }}"
        echo "Running main script..."
        node ${{ github.action_path }}/index.js
      shell: bash
      env:
        DO_API_TOKEN: ${{ inputs.do-api-token }}
        DO_AGENT_BASE_URL: ${{ inputs.do-agent-base-url }}
        FILE_PATTERN: ${{ inputs.file-pattern }}
        EXCLUDE_PATTERN: ${{ inputs.exclude-pattern }}
        GITHUB_TOKEN: ${{ inputs.github-token }}