name: Markdown Grammar Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  grammar-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install axios
          
      - name: Get changed files
        id: changed-files
        uses: actions/github-script@v7
        with:
          script: |
            const github = require('@actions/github');
            const { data: files } = await github.rest.pulls.listFiles({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              pull_number: github.context.payload.pull_request.number,
            });

            const markdownFiles = files
              .map(file => file.filename)
              .filter(name => name.endsWith('.md') && !name.includes('node_modules'));

            core.setOutput("markdown_files", markdownFiles.join(' '));

      - name: Run grammar checks
        if: steps.changed-files.outputs.markdown_files != ''
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DO_AGENT_BASE_URL: ${{ secrets.DO_AGENT_BASE_URL }}
        run: |
          echo "Running grammar checks on changed files..."
          
          files="${{ steps.changed-files.outputs.markdown_files }}"
          
          for file in $files; do
            echo "Checking grammar in $file..."
            node grammar-checker.js "$file"
          done

