name: Markdown Grammar Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  grammar-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install axios
          
      - name: Get changed files
        id: changed-files
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.event.pull_request.base.sha }}
          ref: ${{ github.event.pull_request.head.sha }}
          filters: |
            markdown:
              - '**.md'
              - '!**/node_modules/**'

      - name: Run grammar checks
        if: steps.changed-files.outputs.markdown == 'true'
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
          DO_AGENT_BASE_URL: ${{ secrets.DO_AGENT_BASE_URL }}
        run: |
          echo "Running grammar checks on changed files..."
          
          # Get the list of changed files
          files="${{ steps.changed-files.outputs.files_markdown }}"
          
          # Split files by newlines and process each file
          echo "$files" | while read -r file; do
            if [ -n "$file" ]; then
              echo "Checking grammar in $file..."
              node grammar-checker.js "$file"
            fi
          done
